name: Deploy Flutter to Build Branch

on:
  push:
    branches:
      - dev # Sesuaikan dengan branch utama kamu
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release --base-href "/"

      - name: Deploy to build branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web     # Folder sumber hasil build di runner
          publish_branch: build        # Branch tujuan
          destination_dir: public      # <- MENENTUKAN FOLDER TUJUAN DI BRANCH BUILD
          force_orphan: true
